//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyRegistraAdapter.ProxyRegistraGateway {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string systemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transactionDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channelId {
            get {
                return this.channelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.channelIdField, value) != true)) {
                    this.channelIdField = value;
                    this.RaisePropertyChanged("channelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceNoField, value) != true)) {
                    this.referenceNoField = value;
                    this.RaisePropertyChanged("referenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceNameField, value) != true)) {
                    this.serviceNameField = value;
                    this.RaisePropertyChanged("serviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systemCode {
            get {
                return this.systemCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.systemCodeField, value) != true)) {
                    this.systemCodeField = value;
                    this.RaisePropertyChanged("systemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionDateTimeField, value) != true)) {
                    this.transactionDateTimeField = value;
                    this.RaisePropertyChanged("transactionDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountProxy", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class AccountProxy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProxyRegistraAdapter.ProxyRegistraGateway.AnyID AnyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProxyRegistraAdapter.ProxyRegistraGateway.BankAccount BankAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProxyRegistraAdapter.ProxyRegistraGateway.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DummyAccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyRegistraAdapter.ProxyRegistraGateway.AnyID AnyID {
            get {
                return this.AnyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AnyIDField, value) != true)) {
                    this.AnyIDField = value;
                    this.RaisePropertyChanged("AnyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyRegistraAdapter.ProxyRegistraGateway.BankAccount BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DummyAccountNo {
            get {
                return this.DummyAccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DummyAccountNoField, value) != true)) {
                    this.DummyAccountNoField = value;
                    this.RaisePropertyChanged("DummyAccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationID {
            get {
                return this.RegistrationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationIDField, value) != true)) {
                    this.RegistrationIDField = value;
                    this.RaisePropertyChanged("RegistrationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationTimestamp {
            get {
                return this.RegistrationTimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationTimestampField, value) != true)) {
                    this.RegistrationTimestampField = value;
                    this.RaisePropertyChanged("RegistrationTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnyID", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class AnyID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNo {
            get {
                return this.IDNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IDNoField, value) != true)) {
                    this.IDNoField = value;
                    this.RaisePropertyChanged("IDNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType {
            get {
                return this.IDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IDTypeField, value) != true)) {
                    this.IDTypeField = value;
                    this.RaisePropertyChanged("IDType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class BankAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNoField, value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProxyRegistraAdapter.ProxyRegistraGateway.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProxyRegistraAdapter.ProxyRegistraGateway.Organization))]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CISIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CISID {
            get {
                return this.CISIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CISIDField, value) != true)) {
                    this.CISIDField = value;
                    this.RaisePropertyChanged("CISID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class Person : ProxyRegistraAdapter.ProxyRegistraGateway.Customer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class Organization : ProxyRegistraAdapter.ProxyRegistraGateway.Customer {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisteredDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisteredDate {
            get {
                return this.RegisteredDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisteredDateField, value) != true)) {
                    this.RegisteredDateField = value;
                    this.RaisePropertyChanged("RegisteredDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseMsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.responseCodeField, value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMsg {
            get {
                return this.responseMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.responseMsgField, value) != true)) {
                    this.responseMsgField = value;
                    this.RaisePropertyChanged("responseMsg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyRegistraGateway.IProxyRegistraGateway")]
    public interface IProxyRegistraGateway {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/Register", ReplyAction="http://tempuri.org/IProxyRegistraGateway/RegisterResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.RegisterResponse Register(ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/Register", ReplyAction="http://tempuri.org/IProxyRegistraGateway/RegisterResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.RegisterResponse> RegisterAsync(ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/Amend", ReplyAction="http://tempuri.org/IProxyRegistraGateway/AmendResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.AmendResponse Amend(ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/Amend", ReplyAction="http://tempuri.org/IProxyRegistraGateway/AmendResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.AmendResponse> AmendAsync(ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccount", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountResponse DeactivateByAccount(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccount", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountResponse> DeactivateByAccountAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountNo", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountNoResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoResponse DeactivateByAccountNo(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountNo", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAccountNoResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoResponse> DeactivateByAccountNoAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByRegistrationID", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByRegistrationIDResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDResponse DeactivateByRegistrationID(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByRegistrationID", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByRegistrationIDResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDResponse> DeactivateByRegistrationIDAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAnyID", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAnyIDResponse")]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDResponse DeactivateByAnyID(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistraGateway/DeactivateByAnyID", ReplyAction="http://tempuri.org/IProxyRegistraGateway/DeactivateByAnyIDResponse")]
        System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDResponse> DeactivateByAnyIDAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy) {
            this.header = header;
            this.accountProxy = accountProxy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response RegisterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string registrationID;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response RegisterResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string registrationID) {
            this.RegisterResult = RegisterResult;
            this.header = header;
            this.registrationID = registrationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Amend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AmendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy;
        
        public AmendRequest() {
        }
        
        public AmendRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy) {
            this.header = header;
            this.accountProxy = accountProxy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AmendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AmendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response AmendResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string registrationID;
        
        public AmendResponse() {
        }
        
        public AmendResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response AmendResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string registrationID) {
            this.AmendResult = AmendResult;
            this.header = header;
            this.registrationID = registrationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.BankAccount account;
        
        public DeactivateByAccountRequest() {
        }
        
        public DeactivateByAccountRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.BankAccount account) {
            this.header = header;
            this.account = account;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] registrationIDs;
        
        public DeactivateByAccountResponse() {
        }
        
        public DeactivateByAccountResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccountResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string[] registrationIDs) {
            this.DeactivateByAccountResult = DeactivateByAccountResult;
            this.header = header;
            this.registrationIDs = registrationIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccountNo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAccountNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string accountNo;
        
        public DeactivateByAccountNoRequest() {
        }
        
        public DeactivateByAccountNoRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string accountNo) {
            this.header = header;
            this.accountNo = accountNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccountNoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAccountNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccountNoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] registrationIDs;
        
        public DeactivateByAccountNoResponse() {
        }
        
        public DeactivateByAccountNoResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccountNoResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string[] registrationIDs) {
            this.DeactivateByAccountNoResult = DeactivateByAccountNoResult;
            this.header = header;
            this.registrationIDs = registrationIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByRegistrationID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByRegistrationIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string registrationID;
        
        public DeactivateByRegistrationIDRequest() {
        }
        
        public DeactivateByRegistrationIDRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string registrationID) {
            this.header = header;
            this.registrationID = registrationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByRegistrationIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByRegistrationIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByRegistrationIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        public DeactivateByRegistrationIDResponse() {
        }
        
        public DeactivateByRegistrationIDResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByRegistrationIDResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header) {
            this.DeactivateByRegistrationIDResult = DeactivateByRegistrationIDResult;
            this.header = header;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAnyID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAnyIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.AnyID anyID;
        
        public DeactivateByAnyIDRequest() {
        }
        
        public DeactivateByAnyIDRequest(ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AnyID anyID) {
            this.header = header;
            this.anyID = anyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAnyIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateByAnyIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAnyIDResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ProxyRegistraAdapter.ProxyRegistraGateway.Header header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string registrationID;
        
        public DeactivateByAnyIDResponse() {
        }
        
        public DeactivateByAnyIDResponse(ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAnyIDResult, ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string registrationID) {
            this.DeactivateByAnyIDResult = DeactivateByAnyIDResult;
            this.header = header;
            this.registrationID = registrationID;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyRegistraGatewayChannel : ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyRegistraGatewayClient : System.ServiceModel.ClientBase<ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway>, ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway {
        
        public ProxyRegistraGatewayClient() {
        }
        
        public ProxyRegistraGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyRegistraGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyRegistraGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyRegistraGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.RegisterResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.Register(ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response Register(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy, out string registrationID) {
            ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest();
            inValue.header = header;
            inValue.accountProxy = accountProxy;
            ProxyRegistraAdapter.ProxyRegistraGateway.RegisterResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).Register(inValue);
            header = retVal.header;
            registrationID = retVal.registrationID;
            return retVal.RegisterResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.RegisterResponse> RegisterAsync(ProxyRegistraAdapter.ProxyRegistraGateway.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.AmendResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.Amend(ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest request) {
            return base.Channel.Amend(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response Amend(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AccountProxy accountProxy, out string registrationID) {
            ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest();
            inValue.header = header;
            inValue.accountProxy = accountProxy;
            ProxyRegistraAdapter.ProxyRegistraGateway.AmendResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).Amend(inValue);
            header = retVal.header;
            registrationID = retVal.registrationID;
            return retVal.AmendResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.AmendResponse> AmendAsync(ProxyRegistraAdapter.ProxyRegistraGateway.AmendRequest request) {
            return base.Channel.AmendAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.DeactivateByAccount(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest request) {
            return base.Channel.DeactivateByAccount(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccount(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.BankAccount account, out string[] registrationIDs) {
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest();
            inValue.header = header;
            inValue.account = account;
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).DeactivateByAccount(inValue);
            header = retVal.header;
            registrationIDs = retVal.registrationIDs;
            return retVal.DeactivateByAccountResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountResponse> DeactivateByAccountAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountRequest request) {
            return base.Channel.DeactivateByAccountAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.DeactivateByAccountNo(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest request) {
            return base.Channel.DeactivateByAccountNo(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAccountNo(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string accountNo, out string[] registrationIDs) {
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest();
            inValue.header = header;
            inValue.accountNo = accountNo;
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).DeactivateByAccountNo(inValue);
            header = retVal.header;
            registrationIDs = retVal.registrationIDs;
            return retVal.DeactivateByAccountNoResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoResponse> DeactivateByAccountNoAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAccountNoRequest request) {
            return base.Channel.DeactivateByAccountNoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.DeactivateByRegistrationID(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest request) {
            return base.Channel.DeactivateByRegistrationID(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByRegistrationID(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, string registrationID) {
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest();
            inValue.header = header;
            inValue.registrationID = registrationID;
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).DeactivateByRegistrationID(inValue);
            header = retVal.header;
            return retVal.DeactivateByRegistrationIDResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDResponse> DeactivateByRegistrationIDAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByRegistrationIDRequest request) {
            return base.Channel.DeactivateByRegistrationIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDResponse ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway.DeactivateByAnyID(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest request) {
            return base.Channel.DeactivateByAnyID(request);
        }
        
        public ProxyRegistraAdapter.ProxyRegistraGateway.Response DeactivateByAnyID(ref ProxyRegistraAdapter.ProxyRegistraGateway.Header header, ProxyRegistraAdapter.ProxyRegistraGateway.AnyID anyID, out string registrationID) {
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest inValue = new ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest();
            inValue.header = header;
            inValue.anyID = anyID;
            ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDResponse retVal = ((ProxyRegistraAdapter.ProxyRegistraGateway.IProxyRegistraGateway)(this)).DeactivateByAnyID(inValue);
            header = retVal.header;
            registrationID = retVal.registrationID;
            return retVal.DeactivateByAnyIDResult;
        }
        
        public System.Threading.Tasks.Task<ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDResponse> DeactivateByAnyIDAsync(ProxyRegistraAdapter.ProxyRegistraGateway.DeactivateByAnyIDRequest request) {
            return base.Channel.DeactivateByAnyIDAsync(request);
        }
    }
}
