//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticationTest.KKTAuthentication {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticationTest.KKTAuthentication.ResponseHeader))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticationTest.KKTAuthentication.RequestHeader))]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transReferenceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channelId {
            get {
                return this.channelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.channelIdField, value) != true)) {
                    this.channelIdField = value;
                    this.RaisePropertyChanged("channelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName {
            get {
                return this.serviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.serviceNameField, value) != true)) {
                    this.serviceNameField = value;
                    this.RaisePropertyChanged("serviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transDate {
            get {
                return this.transDateField;
            }
            set {
                if ((object.ReferenceEquals(this.transDateField, value) != true)) {
                    this.transDateField = value;
                    this.RaisePropertyChanged("transDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transReferenceNo {
            get {
                return this.transReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.transReferenceNoField, value) != true)) {
                    this.transReferenceNoField = value;
                    this.RaisePropertyChanged("transReferenceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : AuthenticationTest.KKTAuthentication.Header {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class RequestHeader : AuthenticationTest.KKTAuthentication.Header {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string repeatFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginName {
            get {
                return this.loginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.loginNameField, value) != true)) {
                    this.loginNameField = value;
                    this.RaisePropertyChanged("loginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string repeatFlag {
            get {
                return this.repeatFlagField;
            }
            set {
                if ((object.ReferenceEquals(this.repeatFlagField, value) != true)) {
                    this.repeatFlagField = value;
                    this.RaisePropertyChanged("repeatFlag");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class Authentication : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userPassword {
            get {
                return this.userPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.userPasswordField, value) != true)) {
                    this.userPasswordField = value;
                    this.RaisePropertyChanged("userPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://message.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AuthenticationTest.KKTAuthentication.AuthenticationResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuthenticationTest.KKTAuthentication.ResponseHeader headerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuthenticationTest.KKTAuthentication.ResponseStatus responseStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticationTest.KKTAuthentication.ResponseHeader header {
            get {
                return this.headerField;
            }
            set {
                if ((object.ReferenceEquals(this.headerField, value) != true)) {
                    this.headerField = value;
                    this.RaisePropertyChanged("header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticationTest.KKTAuthentication.ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.responseStatusField, value) != true)) {
                    this.responseStatusField = value;
                    this.RaisePropertyChanged("responseStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class ResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorDesc {
            get {
                return this.errorDescField;
            }
            set {
                if ((object.ReferenceEquals(this.errorDescField, value) != true)) {
                    this.errorDescField = value;
                    this.RaisePropertyChanged("errorDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://message.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class AuthenticationResponse : AuthenticationTest.KKTAuthentication.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuthenticationTest.KKTAuthentication.UserInfo userInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticationTest.KKTAuthentication.UserInfo userInfo {
            get {
                return this.userInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.userInfoField, value) != true)) {
                    this.userInfoField = value;
                    this.RaisePropertyChanged("userInfo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userBranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userBranchNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AuthenticationTest.KKTAuthentication.UserRoles userRolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userBranchName {
            get {
                return this.userBranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userBranchNameField, value) != true)) {
                    this.userBranchNameField = value;
                    this.RaisePropertyChanged("userBranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userBranchNo {
            get {
                return this.userBranchNoField;
            }
            set {
                if ((object.ReferenceEquals(this.userBranchNoField, value) != true)) {
                    this.userBranchNoField = value;
                    this.RaisePropertyChanged("userBranchNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userFullName {
            get {
                return this.userFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userFullNameField, value) != true)) {
                    this.userFullNameField = value;
                    this.RaisePropertyChanged("userFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                if ((object.ReferenceEquals(this.userIdField, value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AuthenticationTest.KKTAuthentication.UserRoles userRoles {
            get {
                return this.userRolesField;
            }
            set {
                if ((object.ReferenceEquals(this.userRolesField, value) != true)) {
                    this.userRolesField = value;
                    this.RaisePropertyChanged("userRoles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserRoles", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd", ItemName="userRoles")]
    [System.SerializableAttribute()]
    public class UserRoles : System.Collections.Generic.List<AuthenticationTest.KKTAuthentication.UserRole> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    [System.SerializableAttribute()]
    public partial class UserRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roleCode {
            get {
                return this.roleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.roleCodeField, value) != true)) {
                    this.roleCodeField = value;
                    this.RaisePropertyChanged("roleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roleName {
            get {
                return this.roleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.roleNameField, value) != true)) {
                    this.roleNameField = value;
                    this.RaisePropertyChanged("roleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.authentication.kktutility.services.kiatnakinbank.com", ConfigurationName="KKTAuthentication.KKTAuthenticationPortType")]
    public interface KKTAuthenticationPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:authenticate", ReplyAction="urn:authenticateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AuthenticationTest.KKTAuthentication.AuthenticationResponse authenticate(AuthenticationTest.KKTAuthentication.RequestHeader header, AuthenticationTest.KKTAuthentication.Authentication authentication);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:authenticate", ReplyAction="urn:authenticateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<AuthenticationTest.KKTAuthentication.AuthenticationResponse> authenticateAsync(AuthenticationTest.KKTAuthentication.RequestHeader header, AuthenticationTest.KKTAuthentication.Authentication authentication);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KKTAuthenticationPortTypeChannel : AuthenticationTest.KKTAuthentication.KKTAuthenticationPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KKTAuthenticationPortTypeClient : System.ServiceModel.ClientBase<AuthenticationTest.KKTAuthentication.KKTAuthenticationPortType>, AuthenticationTest.KKTAuthentication.KKTAuthenticationPortType {
        
        public KKTAuthenticationPortTypeClient() {
        }
        
        public KKTAuthenticationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KKTAuthenticationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KKTAuthenticationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KKTAuthenticationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AuthenticationTest.KKTAuthentication.AuthenticationResponse authenticate(AuthenticationTest.KKTAuthentication.RequestHeader header, AuthenticationTest.KKTAuthentication.Authentication authentication) {
            return base.Channel.authenticate(header, authentication);
        }
        
        public System.Threading.Tasks.Task<AuthenticationTest.KKTAuthentication.AuthenticationResponse> authenticateAsync(AuthenticationTest.KKTAuthentication.RequestHeader header, AuthenticationTest.KKTAuthentication.Authentication authentication) {
            return base.Channel.authenticateAsync(header, authentication);
        }
    }
}
