//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyRegistraGateway
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string channelIdField;
        
        private string referenceNoField;
        
        private string serviceNameField;
        
        private string systemCodeField;
        
        private string transactionDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channelId
        {
            get
            {
                return this.channelIdField;
            }
            set
            {
                this.channelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string referenceNo
        {
            get
            {
                return this.referenceNoField;
            }
            set
            {
                this.referenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string systemCode
        {
            get
            {
                return this.systemCodeField;
            }
            set
            {
                this.systemCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transactionDateTime
        {
            get
            {
                return this.transactionDateTimeField;
            }
            set
            {
                this.transactionDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/ProxyRegistraGateway")]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string responseCodeField;
        
        private string responseMsgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMsg
        {
            get
            {
                return this.responseMsgField;
            }
            set
            {
                this.responseMsgField = value;
            }
        }
    }
}
namespace iSabaya
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersistentEntity", Namespace="http://schemas.datacontract.org/2004/07/iSabaya")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSabaya.PersistentTemporalEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSabaya.BankAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.Customer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.Organization))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.AnyID))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSabaya.PersistentStatefulEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.AccountProxy))]
    public partial class PersistentEntity : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersistentTemporalEntity", Namespace="http://schemas.datacontract.org/2004/07/iSabaya")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(iSabaya.BankAccount))]
    public partial class PersistentTemporalEntity : iSabaya.PersistentEntity
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccount", Namespace="http://schemas.datacontract.org/2004/07/iSabaya")]
    public partial class BankAccount : iSabaya.PersistentTemporalEntity
    {
        
        private string AccountNoField;
        
        private string NameField;
        
        private iSabaya.BankAccountStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo
        {
            get
            {
                return this.AccountNoField;
            }
            set
            {
                this.AccountNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iSabaya.BankAccountStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersistentStatefulEntity", Namespace="http://schemas.datacontract.org/2004/07/iSabaya")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.AccountProxy))]
    public partial class PersistentStatefulEntity : iSabaya.PersistentEntity
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccountStatus", Namespace="http://schemas.datacontract.org/2004/07/iSabaya")]
    public enum BankAccountStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Closed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Frozen = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dormant = 3,
    }
}
namespace AnyIDModel
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.Person))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AnyIDModel.Organization))]
    public partial class Customer : iSabaya.PersistentEntity
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public partial class Person : AnyIDModel.Customer
    {
        
        private string FirstNameEnglishField;
        
        private string FirstNameThaiField;
        
        private string LastNameEnglishField;
        
        private string LastNameThaiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameEnglish
        {
            get
            {
                return this.FirstNameEnglishField;
            }
            set
            {
                this.FirstNameEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstNameThai
        {
            get
            {
                return this.FirstNameThaiField;
            }
            set
            {
                this.FirstNameThaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameEnglish
        {
            get
            {
                return this.LastNameEnglishField;
            }
            set
            {
                this.LastNameEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNameThai
        {
            get
            {
                return this.LastNameThaiField;
            }
            set
            {
                this.LastNameThaiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public partial class Organization : AnyIDModel.Customer
    {
        
        private string NameEnglishField;
        
        private string NameThaiField;
        
        private System.DateTime RegisteredDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameEnglish
        {
            get
            {
                return this.NameEnglishField;
            }
            set
            {
                this.NameEnglishField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameThai
        {
            get
            {
                return this.NameThaiField;
            }
            set
            {
                this.NameThaiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredDate
        {
            get
            {
                return this.RegisteredDateField;
            }
            set
            {
                this.RegisteredDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnyID", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public partial class AnyID : iSabaya.PersistentEntity
    {
        
        private string IDNoField;
        
        private AnyIDModel.AnyIDType IDTypeField;
        
        private AnyIDModel.AnyIDStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNo
        {
            get
            {
                return this.IDNoField;
            }
            set
            {
                this.IDNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnyIDModel.AnyIDType IDType
        {
            get
            {
                return this.IDTypeField;
            }
            set
            {
                this.IDTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnyIDModel.AnyIDStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountProxy", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public partial class AccountProxy : iSabaya.PersistentStatefulEntity
    {
        
        private AnyIDModel.AnyID AnyIDField;
        
        private iSabaya.BankAccount BankAccountField;
        
        private AnyIDModel.Customer CustomerField;
        
        private string DisplayNameField;
        
        private string DummyAccountNoField;
        
        private System.DateTime RegisteredTSField;
        
        private string RegistrationIDField;
        
        private AnyIDModel.EntityStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnyIDModel.AnyID AnyID
        {
            get
            {
                return this.AnyIDField;
            }
            set
            {
                this.AnyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public iSabaya.BankAccount BankAccount
        {
            get
            {
                return this.BankAccountField;
            }
            set
            {
                this.BankAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnyIDModel.Customer Customer
        {
            get
            {
                return this.CustomerField;
            }
            set
            {
                this.CustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DummyAccountNo
        {
            get
            {
                return this.DummyAccountNoField;
            }
            set
            {
                this.DummyAccountNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisteredTS
        {
            get
            {
                return this.RegisteredTSField;
            }
            set
            {
                this.RegisteredTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationID
        {
            get
            {
                return this.RegistrationIDField;
            }
            set
            {
                this.RegistrationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AnyIDModel.EntityStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityStatus", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public enum EntityStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnyIDType", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public enum AnyIDType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSISDN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NATID = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnyIDStatus", Namespace="http://schemas.datacontract.org/2004/07/AnyIDModel")]
    public enum AnyIDStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Registering = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNSUB = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUBSCR = 2,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IProxyRegistra")]
public interface IProxyRegistra
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/Register", ReplyAction="http://tempuri.org/IProxyRegistra/RegisterResponse")]
    RegisterResponse Register(RegisterRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/Register", ReplyAction="http://tempuri.org/IProxyRegistra/RegisterResponse")]
    System.Threading.Tasks.Task<RegisterResponse> RegisterAsync(RegisterRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/Amend", ReplyAction="http://tempuri.org/IProxyRegistra/AmendResponse")]
    AmendResponse Amend(AmendRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/Amend", ReplyAction="http://tempuri.org/IProxyRegistra/AmendResponse")]
    System.Threading.Tasks.Task<AmendResponse> AmendAsync(AmendRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByAccount", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByAccountResponse")]
    DeactivateByAccountResponse DeactivateByAccount(DeactivateByAccountRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByAccount", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByAccountResponse")]
    System.Threading.Tasks.Task<DeactivateByAccountResponse> DeactivateByAccountAsync(DeactivateByAccountRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByRegistrationID", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByRegistrationIDResponse")]
    DeactivateByRegistrationIDResponse DeactivateByRegistrationID(DeactivateByRegistrationIDRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByRegistrationID", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByRegistrationIDResponse")]
    System.Threading.Tasks.Task<DeactivateByRegistrationIDResponse> DeactivateByRegistrationIDAsync(DeactivateByRegistrationIDRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByAnyID", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByAnyIDResponse")]
    DeactivateByAnyIDResponse DeactivateByAnyID(DeactivateByAnyIDRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyRegistra/DeactivateByAnyID", ReplyAction="http://tempuri.org/IProxyRegistra/DeactivateByAnyIDResponse")]
    System.Threading.Tasks.Task<DeactivateByAnyIDResponse> DeactivateByAnyIDAsync(DeactivateByAnyIDRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Register", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class RegisterRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public AnyIDModel.AccountProxy accountProxy;
    
    public RegisterRequest()
    {
    }
    
    public RegisterRequest(ProxyRegistraGateway.Header header, AnyIDModel.AccountProxy accountProxy)
    {
        this.header = header;
        this.accountProxy = accountProxy;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="RegisterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class RegisterResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Response RegisterResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string registrationID;
    
    public RegisterResponse()
    {
    }
    
    public RegisterResponse(ProxyRegistraGateway.Response RegisterResult, ProxyRegistraGateway.Header header, string registrationID)
    {
        this.RegisterResult = RegisterResult;
        this.header = header;
        this.registrationID = registrationID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="Amend", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class AmendRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public AnyIDModel.AccountProxy accountProxy;
    
    public AmendRequest()
    {
    }
    
    public AmendRequest(ProxyRegistraGateway.Header header, AnyIDModel.AccountProxy accountProxy)
    {
        this.header = header;
        this.accountProxy = accountProxy;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="AmendResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class AmendResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Response AmendResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string registrationID;
    
    public AmendResponse()
    {
    }
    
    public AmendResponse(ProxyRegistraGateway.Response AmendResult, ProxyRegistraGateway.Header header, string registrationID)
    {
        this.AmendResult = AmendResult;
        this.header = header;
        this.registrationID = registrationID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByAccountRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string accountNo;
    
    public DeactivateByAccountRequest()
    {
    }
    
    public DeactivateByAccountRequest(ProxyRegistraGateway.Header header, string accountNo)
    {
        this.header = header;
        this.accountNo = accountNo;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAccountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByAccountResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Response DeactivateByAccountResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string[] registrationIDs;
    
    public DeactivateByAccountResponse()
    {
    }
    
    public DeactivateByAccountResponse(ProxyRegistraGateway.Response DeactivateByAccountResult, ProxyRegistraGateway.Header header, string[] registrationIDs)
    {
        this.DeactivateByAccountResult = DeactivateByAccountResult;
        this.header = header;
        this.registrationIDs = registrationIDs;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByRegistrationID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByRegistrationIDRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public string registrationID;
    
    public DeactivateByRegistrationIDRequest()
    {
    }
    
    public DeactivateByRegistrationIDRequest(ProxyRegistraGateway.Header header, string registrationID)
    {
        this.header = header;
        this.registrationID = registrationID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByRegistrationIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByRegistrationIDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Response DeactivateByRegistrationIDResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ProxyRegistraGateway.Header header;
    
    public DeactivateByRegistrationIDResponse()
    {
    }
    
    public DeactivateByRegistrationIDResponse(ProxyRegistraGateway.Response DeactivateByRegistrationIDResult, ProxyRegistraGateway.Header header)
    {
        this.DeactivateByRegistrationIDResult = DeactivateByRegistrationIDResult;
        this.header = header;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAnyID", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByAnyIDRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public AnyIDModel.AnyID anyID;
    
    public DeactivateByAnyIDRequest()
    {
    }
    
    public DeactivateByAnyIDRequest(ProxyRegistraGateway.Header header, AnyIDModel.AnyID anyID)
    {
        this.header = header;
        this.anyID = anyID;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateByAnyIDResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DeactivateByAnyIDResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public ProxyRegistraGateway.Response DeactivateByAnyIDResult;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
    public ProxyRegistraGateway.Header header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
    public string registrationID;
    
    public DeactivateByAnyIDResponse()
    {
    }
    
    public DeactivateByAnyIDResponse(ProxyRegistraGateway.Response DeactivateByAnyIDResult, ProxyRegistraGateway.Header header, string registrationID)
    {
        this.DeactivateByAnyIDResult = DeactivateByAnyIDResult;
        this.header = header;
        this.registrationID = registrationID;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IProxyRegistraChannel : IProxyRegistra, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProxyRegistraClient : System.ServiceModel.ClientBase<IProxyRegistra>, IProxyRegistra
{
    
    public ProxyRegistraClient()
    {
    }
    
    public ProxyRegistraClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ProxyRegistraClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProxyRegistraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ProxyRegistraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RegisterResponse IProxyRegistra.Register(RegisterRequest request)
    {
        return base.Channel.Register(request);
    }
    
    public ProxyRegistraGateway.Response Register(ref ProxyRegistraGateway.Header header, AnyIDModel.AccountProxy accountProxy, out string registrationID)
    {
        RegisterRequest inValue = new RegisterRequest();
        inValue.header = header;
        inValue.accountProxy = accountProxy;
        RegisterResponse retVal = ((IProxyRegistra)(this)).Register(inValue);
        header = retVal.header;
        registrationID = retVal.registrationID;
        return retVal.RegisterResult;
    }
    
    public System.Threading.Tasks.Task<RegisterResponse> RegisterAsync(RegisterRequest request)
    {
        return base.Channel.RegisterAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AmendResponse IProxyRegistra.Amend(AmendRequest request)
    {
        return base.Channel.Amend(request);
    }
    
    public ProxyRegistraGateway.Response Amend(ref ProxyRegistraGateway.Header header, AnyIDModel.AccountProxy accountProxy, out string registrationID)
    {
        AmendRequest inValue = new AmendRequest();
        inValue.header = header;
        inValue.accountProxy = accountProxy;
        AmendResponse retVal = ((IProxyRegistra)(this)).Amend(inValue);
        header = retVal.header;
        registrationID = retVal.registrationID;
        return retVal.AmendResult;
    }
    
    public System.Threading.Tasks.Task<AmendResponse> AmendAsync(AmendRequest request)
    {
        return base.Channel.AmendAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeactivateByAccountResponse IProxyRegistra.DeactivateByAccount(DeactivateByAccountRequest request)
    {
        return base.Channel.DeactivateByAccount(request);
    }
    
    public ProxyRegistraGateway.Response DeactivateByAccount(ref ProxyRegistraGateway.Header header, string accountNo, out string[] registrationIDs)
    {
        DeactivateByAccountRequest inValue = new DeactivateByAccountRequest();
        inValue.header = header;
        inValue.accountNo = accountNo;
        DeactivateByAccountResponse retVal = ((IProxyRegistra)(this)).DeactivateByAccount(inValue);
        header = retVal.header;
        registrationIDs = retVal.registrationIDs;
        return retVal.DeactivateByAccountResult;
    }
    
    public System.Threading.Tasks.Task<DeactivateByAccountResponse> DeactivateByAccountAsync(DeactivateByAccountRequest request)
    {
        return base.Channel.DeactivateByAccountAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeactivateByRegistrationIDResponse IProxyRegistra.DeactivateByRegistrationID(DeactivateByRegistrationIDRequest request)
    {
        return base.Channel.DeactivateByRegistrationID(request);
    }
    
    public ProxyRegistraGateway.Response DeactivateByRegistrationID(ref ProxyRegistraGateway.Header header, string registrationID)
    {
        DeactivateByRegistrationIDRequest inValue = new DeactivateByRegistrationIDRequest();
        inValue.header = header;
        inValue.registrationID = registrationID;
        DeactivateByRegistrationIDResponse retVal = ((IProxyRegistra)(this)).DeactivateByRegistrationID(inValue);
        header = retVal.header;
        return retVal.DeactivateByRegistrationIDResult;
    }
    
    public System.Threading.Tasks.Task<DeactivateByRegistrationIDResponse> DeactivateByRegistrationIDAsync(DeactivateByRegistrationIDRequest request)
    {
        return base.Channel.DeactivateByRegistrationIDAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    DeactivateByAnyIDResponse IProxyRegistra.DeactivateByAnyID(DeactivateByAnyIDRequest request)
    {
        return base.Channel.DeactivateByAnyID(request);
    }
    
    public ProxyRegistraGateway.Response DeactivateByAnyID(ref ProxyRegistraGateway.Header header, AnyIDModel.AnyID anyID, out string registrationID)
    {
        DeactivateByAnyIDRequest inValue = new DeactivateByAnyIDRequest();
        inValue.header = header;
        inValue.anyID = anyID;
        DeactivateByAnyIDResponse retVal = ((IProxyRegistra)(this)).DeactivateByAnyID(inValue);
        header = retVal.header;
        registrationID = retVal.registrationID;
        return retVal.DeactivateByAnyIDResult;
    }
    
    public System.Threading.Tasks.Task<DeactivateByAnyIDResponse> DeactivateByAnyIDAsync(DeactivateByAnyIDRequest request)
    {
        return base.Channel.DeactivateByAnyIDAsync(request);
    }
}
