//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.kiatnakinbank.com/services/CAA/CAACommon/data", ClrNamespace="www.kiatnakinbank.com.services.CAA.CAACommon.data")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.kiatnakinbank.com/services/CAA/CAATokenService/data", ClrNamespace="www.kiatnakinbank.com.services.CAA.CAATokenService.data")]

namespace www.kiatnakinbank.com.services.CAA.CAACommon.data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://www.kiatnakinbank.com/services/CAA/CAACommon/data")]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ReferenceNoField;
        
        private string TransactionDateTimeField;
        
        private string ServiceNameField;
        
        private string SystemCodeField;
        
        private string ChannelIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReferenceNo
        {
            get
            {
                return this.ReferenceNoField;
            }
            set
            {
                this.ReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TransactionDateTime
        {
            get
            {
                return this.TransactionDateTimeField;
            }
            set
            {
                this.TransactionDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string SystemCode
        {
            get
            {
                return this.SystemCodeField;
            }
            set
            {
                this.SystemCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ChannelID
        {
            get
            {
                return this.ChannelIDField;
            }
            set
            {
                this.ChannelIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://www.kiatnakinbank.com/services/CAA/CAACommon/data")]
    public partial class ResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseCode
        {
            get
            {
                return this.ResponseCodeField;
            }
            set
            {
                this.ResponseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseMessage
        {
            get
            {
                return this.ResponseMessageField;
            }
            set
            {
                this.ResponseMessageField = value;
            }
        }
    }
}
namespace www.kiatnakinbank.com.services.CAA.CAATokenService.data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateOTPParam", Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/data")]
    public partial class GenerateOTPParam : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MobileNumberField;
        
        private string TemplateField;
        
        private string PolicyField;
        
        private www.kiatnakinbank.com.services.CAA.CAATokenService.data.MessageParam MessageParamField;
        
        private string ClientIpField;
        
        private string OldTokenUUIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Template
        {
            get
            {
                return this.TemplateField;
            }
            set
            {
                this.TemplateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Policy
        {
            get
            {
                return this.PolicyField;
            }
            set
            {
                this.PolicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public www.kiatnakinbank.com.services.CAA.CAATokenService.data.MessageParam MessageParam
        {
            get
            {
                return this.MessageParamField;
            }
            set
            {
                this.MessageParamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ClientIp
        {
            get
            {
                return this.ClientIpField;
            }
            set
            {
                this.ClientIpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string OldTokenUUID
        {
            get
            {
                return this.OldTokenUUIDField;
            }
            set
            {
                this.OldTokenUUIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageParam", Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/data")]
    public partial class MessageParam : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MsgPrefixField;
        
        private string MsgDetailField;
        
        private string MsgSuffixField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgPrefix
        {
            get
            {
                return this.MsgPrefixField;
            }
            set
            {
                this.MsgPrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MsgDetail
        {
            get
            {
                return this.MsgDetailField;
            }
            set
            {
                this.MsgDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MsgSuffix
        {
            get
            {
                return this.MsgSuffixField;
            }
            set
            {
                this.MsgSuffixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateOTPDetail", Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/data")]
    public partial class GenerateOTPDetail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TokenUUIDField;
        
        private string ReferenceNoField;
        
        private string OTPTimeoutField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenUUID
        {
            get
            {
                return this.TokenUUIDField;
            }
            set
            {
                this.TokenUUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReferenceNo
        {
            get
            {
                return this.ReferenceNoField;
            }
            set
            {
                this.ReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OTPTimeout
        {
            get
            {
                return this.OTPTimeoutField;
            }
            set
            {
                this.OTPTimeoutField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyOTPParam", Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/data")]
    public partial class VerifyOTPParam : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TokenUUIDField;
        
        private string ReferenceNoField;
        
        private string OTPField;
        
        private string ClientIpField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenUUID
        {
            get
            {
                return this.TokenUUIDField;
            }
            set
            {
                this.TokenUUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReferenceNo
        {
            get
            {
                return this.ReferenceNoField;
            }
            set
            {
                this.ReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OTP
        {
            get
            {
                return this.OTPField;
            }
            set
            {
                this.OTPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ClientIp
        {
            get
            {
                return this.ClientIpField;
            }
            set
            {
                this.ClientIpField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", ConfigurationName="ICAATokenService")]
public interface ICAATokenService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Genera" +
        "teOTP", ReplyAction="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Genera" +
        "teOTPResponse")]
    GenerateOTPResponse GenerateOTP(GenerateOTPRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Genera" +
        "teOTP", ReplyAction="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Genera" +
        "teOTPResponse")]
    System.Threading.Tasks.Task<GenerateOTPResponse> GenerateOTPAsync(GenerateOTPRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Verify" +
        "OTP", ReplyAction="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Verify" +
        "OTPResponse")]
    VerifyOTPResponse VerifyOTP(VerifyOTPRequest request);
    
    // CODEGEN: Generating message contract since the operation has multiple return values.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Verify" +
        "OTP", ReplyAction="http://www.kiatnakinbank.com/services/CAA/CAATokenService/ICAATokenService/Verify" +
        "OTPResponse")]
    System.Threading.Tasks.Task<VerifyOTPResponse> VerifyOTPAsync(VerifyOTPRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GenerateOTPRequest", WrapperNamespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/message", IsWrapped=true)]
public partial class GenerateOTPRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=0)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=1)]
    public www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPParam GenerateOTPParam;
    
    public GenerateOTPRequest()
    {
    }
    
    public GenerateOTPRequest(www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPParam GenerateOTPParam)
    {
        this.Header = Header;
        this.GenerateOTPParam = GenerateOTPParam;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GenerateOTPResponse", WrapperNamespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/message", IsWrapped=true)]
public partial class GenerateOTPResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=0)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=1)]
    public www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPDetail GenerateOTPDetail;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=2)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus ResponseStatus;
    
    public GenerateOTPResponse()
    {
    }
    
    public GenerateOTPResponse(www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPDetail GenerateOTPDetail, www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus ResponseStatus)
    {
        this.Header = Header;
        this.GenerateOTPDetail = GenerateOTPDetail;
        this.ResponseStatus = ResponseStatus;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VerifyOTPRequest", WrapperNamespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/message", IsWrapped=true)]
public partial class VerifyOTPRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=0)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=1)]
    public www.kiatnakinbank.com.services.CAA.CAATokenService.data.VerifyOTPParam VerifyOTPParam;
    
    public VerifyOTPRequest()
    {
    }
    
    public VerifyOTPRequest(www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAATokenService.data.VerifyOTPParam VerifyOTPParam)
    {
        this.Header = Header;
        this.VerifyOTPParam = VerifyOTPParam;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="VerifyOTPResponse", WrapperNamespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService/message", IsWrapped=true)]
public partial class VerifyOTPResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=0)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.kiatnakinbank.com/services/CAA/CAATokenService", Order=1)]
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus ResponseStatus;
    
    public VerifyOTPResponse()
    {
    }
    
    public VerifyOTPResponse(www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus ResponseStatus)
    {
        this.Header = Header;
        this.ResponseStatus = ResponseStatus;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICAATokenServiceChannel : ICAATokenService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CAATokenServiceClient : System.ServiceModel.ClientBase<ICAATokenService>, ICAATokenService
{
    
    public CAATokenServiceClient()
    {
    }
    
    public CAATokenServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CAATokenServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CAATokenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CAATokenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GenerateOTPResponse ICAATokenService.GenerateOTP(GenerateOTPRequest request)
    {
        return base.Channel.GenerateOTP(request);
    }
    
    public www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPDetail GenerateOTP(ref www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAATokenService.data.GenerateOTPParam GenerateOTPParam, out www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus ResponseStatus)
    {
        GenerateOTPRequest inValue = new GenerateOTPRequest();
        inValue.Header = Header;
        inValue.GenerateOTPParam = GenerateOTPParam;
        GenerateOTPResponse retVal = ((ICAATokenService)(this)).GenerateOTP(inValue);
        Header = retVal.Header;
        ResponseStatus = retVal.ResponseStatus;
        return retVal.GenerateOTPDetail;
    }
    
    public System.Threading.Tasks.Task<GenerateOTPResponse> GenerateOTPAsync(GenerateOTPRequest request)
    {
        return base.Channel.GenerateOTPAsync(request);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    VerifyOTPResponse ICAATokenService.VerifyOTP(VerifyOTPRequest request)
    {
        return base.Channel.VerifyOTP(request);
    }
    
    public www.kiatnakinbank.com.services.CAA.CAACommon.data.ResponseStatus VerifyOTP(ref www.kiatnakinbank.com.services.CAA.CAACommon.data.Header Header, www.kiatnakinbank.com.services.CAA.CAATokenService.data.VerifyOTPParam VerifyOTPParam)
    {
        VerifyOTPRequest inValue = new VerifyOTPRequest();
        inValue.Header = Header;
        inValue.VerifyOTPParam = VerifyOTPParam;
        VerifyOTPResponse retVal = ((ICAATokenService)(this)).VerifyOTP(inValue);
        Header = retVal.Header;
        return retVal.ResponseStatus;
    }
    
    public System.Threading.Tasks.Task<VerifyOTPResponse> VerifyOTPAsync(VerifyOTPRequest request)
    {
        return base.Channel.VerifyOTPAsync(request);
    }
}
