//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dto.kktutility.services.kiatnakinbank.com/xsd", ClrNamespace="dto.kktutility.services.kiatnakinbank.com.xsd")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd", ClrNamespace="dto.authentication.kktutility.services.kiatnakinbank.com.xsd")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://message.kktutility.services.kiatnakinbank.com/xsd", ClrNamespace="message.kktutility.services.kiatnakinbank.com.xsd")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://message.authentication.kktutility.services.kiatnakinbank.com/xsd", ClrNamespace="message.authentication.kktutility.services.kiatnakinbank.com.xsd")]

namespace dto.kktutility.services.kiatnakinbank.com.xsd
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dto.kktutility.services.kiatnakinbank.com.xsd.ResponseHeader))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dto.kktutility.services.kiatnakinbank.com.xsd.RequestHeader))]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string channelIdField;
        
        private string serviceNameField;
        
        private string transDateField;
        
        private string transReferenceNoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channelId
        {
            get
            {
                return this.channelIdField;
            }
            set
            {
                this.channelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transDate
        {
            get
            {
                return this.transDateField;
            }
            set
            {
                this.transDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string transReferenceNo
        {
            get
            {
                return this.transReferenceNoField;
            }
            set
            {
                this.transReferenceNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class ResponseHeader : dto.kktutility.services.kiatnakinbank.com.xsd.Header
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class RequestHeader : dto.kktutility.services.kiatnakinbank.com.xsd.Header
    {
        
        private string loginNameField;
        
        private string loginPasswordField;
        
        private string repeatFlagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginName
        {
            get
            {
                return this.loginNameField;
            }
            set
            {
                this.loginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword
        {
            get
            {
                return this.loginPasswordField;
            }
            set
            {
                this.loginPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string repeatFlag
        {
            get
            {
                return this.repeatFlagField;
            }
            set
            {
                this.repeatFlagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://dto.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class ResponseStatus : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string errorCodeField;
        
        private string errorDescField;
        
        private string statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorDesc
        {
            get
            {
                return this.errorDescField;
            }
            set
            {
                this.errorDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
}
namespace dto.authentication.kktutility.services.kiatnakinbank.com.xsd
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authentication", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class Authentication : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userIdField;
        
        private string userPasswordField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userPassword
        {
            get
            {
                return this.userPasswordField;
            }
            set
            {
                this.userPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string userBranchNameField;
        
        private string userBranchNoField;
        
        private string userFullNameField;
        
        private string userIdField;
        
        private dto.authentication.kktutility.services.kiatnakinbank.com.xsd.UserRoles userRolesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userBranchName
        {
            get
            {
                return this.userBranchNameField;
            }
            set
            {
                this.userBranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userBranchNo
        {
            get
            {
                return this.userBranchNoField;
            }
            set
            {
                this.userBranchNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userFullName
        {
            get
            {
                return this.userFullNameField;
            }
            set
            {
                this.userFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dto.authentication.kktutility.services.kiatnakinbank.com.xsd.UserRoles userRoles
        {
            get
            {
                return this.userRolesField;
            }
            set
            {
                this.userRolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserRoles", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd", ItemName="userRoles")]
    public class UserRoles : System.Collections.Generic.List<dto.authentication.kktutility.services.kiatnakinbank.com.xsd.UserRole>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://dto.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class UserRole : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string roleCodeField;
        
        private string roleNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roleCode
        {
            get
            {
                return this.roleCodeField;
            }
            set
            {
                this.roleCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string roleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }
    }
}
namespace message.kktutility.services.kiatnakinbank.com.xsd
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://message.kktutility.services.kiatnakinbank.com/xsd")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(message.authentication.kktutility.services.kiatnakinbank.com.xsd.AuthenticationResponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private dto.kktutility.services.kiatnakinbank.com.xsd.ResponseHeader headerField;
        
        private dto.kktutility.services.kiatnakinbank.com.xsd.ResponseStatus responseStatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dto.kktutility.services.kiatnakinbank.com.xsd.ResponseHeader header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dto.kktutility.services.kiatnakinbank.com.xsd.ResponseStatus responseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
    }
}
namespace message.authentication.kktutility.services.kiatnakinbank.com.xsd
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResponse", Namespace="http://message.authentication.kktutility.services.kiatnakinbank.com/xsd")]
    public partial class AuthenticationResponse : message.kktutility.services.kiatnakinbank.com.xsd.Response
    {
        
        private dto.authentication.kktutility.services.kiatnakinbank.com.xsd.UserInfo userInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dto.authentication.kktutility.services.kiatnakinbank.com.xsd.UserInfo userInfo
        {
            get
            {
                return this.userInfoField;
            }
            set
            {
                this.userInfoField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://service.authentication.kktutility.services.kiatnakinbank.com", ConfigurationName="KKTAuthenticationPortType")]
public interface KKTAuthenticationPortType
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:authenticate", ReplyAction="urn:authenticateResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    message.authentication.kktutility.services.kiatnakinbank.com.xsd.AuthenticationResponse authenticate(dto.kktutility.services.kiatnakinbank.com.xsd.RequestHeader header, dto.authentication.kktutility.services.kiatnakinbank.com.xsd.Authentication authentication);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:authenticate", ReplyAction="urn:authenticateResponse")]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    System.Threading.Tasks.Task<message.authentication.kktutility.services.kiatnakinbank.com.xsd.AuthenticationResponse> authenticateAsync(dto.kktutility.services.kiatnakinbank.com.xsd.RequestHeader header, dto.authentication.kktutility.services.kiatnakinbank.com.xsd.Authentication authentication);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface KKTAuthenticationPortTypeChannel : KKTAuthenticationPortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class KKTAuthenticationPortTypeClient : System.ServiceModel.ClientBase<KKTAuthenticationPortType>, KKTAuthenticationPortType
{
    
    public KKTAuthenticationPortTypeClient()
    {
    }
    
    public KKTAuthenticationPortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public KKTAuthenticationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public KKTAuthenticationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public KKTAuthenticationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public message.authentication.kktutility.services.kiatnakinbank.com.xsd.AuthenticationResponse authenticate(dto.kktutility.services.kiatnakinbank.com.xsd.RequestHeader header, dto.authentication.kktutility.services.kiatnakinbank.com.xsd.Authentication authentication)
    {
        return base.Channel.authenticate(header, authentication);
    }
    
    public System.Threading.Tasks.Task<message.authentication.kktutility.services.kiatnakinbank.com.xsd.AuthenticationResponse> authenticateAsync(dto.kktutility.services.kiatnakinbank.com.xsd.RequestHeader header, dto.authentication.kktutility.services.kiatnakinbank.com.xsd.Authentication authentication)
    {
        return base.Channel.authenticateAsync(header, authentication);
    }
}
